### ISSUE TITLE
wd_get_accel_list() is cheaper than wd_get_accel_dev()

### ISSUE THREAD

**Issue by docularxu** [Linaro/uadk_engine#121]
Because wd_get_accel_list() is cheaper than wd_get_accel_dev(), in this function, it's better to call wd_get_accel_list().

When you call wd_get_accel_dev(), it still calls 'wd_get_accel_list()', then it traverses the list, then it returns a *dev which has no real use in bind_fn_uadk_alg().

https://github.com/Linaro/uadk_engine/blob/50692e4bc425c5709a468946cb56ad483be90f7c/src/e_uadk.c#L287

**Comment by docularxu** [comment]
Refer to commit id: 8539435f191790a3d92a2ecdd6b47b55a789758e

**Comment by gaozhangfei** [comment]
不改可以的，一个获取全部设备，一个获取numa 最近的设备
为Null就是没有可用设备.
