### ISSUE TITLE
README: move test cases from README to a seperate file

### ISSUE THREAD

**Issue by docularxu** [Linaro/uadk_engine#127]
Too many test commands was listed in the README.
Suggest to move them out, and put into a new file.

https://github.com/Linaro/uadk_engine/blob/1b8b65e31da0c6347575d0d201c8417241e81453/README#L68

These test commands are not the same as what's in ``test/sanity_test.sh``. I suppose they have different use.

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/uadk_engine/pull/128
