### ISSUE TITLE
Bug: it's better to compare the content of two strings instead of their address

### ISSUE THREAD

**Issue by docularxu** [Linaro/uadk_engine#131]
```
e_uadk.c:int uadk_e_is_env_enabled(const char *alg_name)

		if (uadk_env_enabled[i].alg_name == alg_name) {
```
This comparison is not good. It leaves some potential bugs to the user of this function.

Although most compilers keep const strings in the same region, but the caller still has to make sure that they won't pass a runtime-string address into this function.

Eg.
 ```
char algo[]="cipher";
uadk_e_is_env_enabled(algo);
```
will return a failure.

Ref: https://github.com/Linaro/uadk_engine/blob/5dab65ce804d8e7995cef2eecfb375270d55f2ed/src/e_uadk.c#L119

**Comment by gaozhangfei** [comment]
closed by pull/132
