### ISSUE TITLE
README need to update for pkgconfig

### ISSUE THREAD

**Issue by KeyiZhong** [Linaro/uadk_engine#151]
_**Build & Install OpenSSL UADK Engine**_ session should have enviroment variable `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`

**Comment by gaozhangfei** [comment]
Suppose this is openEuler issue, has submitted an issue, though no reply yet.

https://gitee.com/openeuler/community/issues/I65ASD?from=project-issue

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/uadk_engine/pull/159
