### ISSUE TITLE
Forced dependency on 'default' provider, this is not a good design.

### ISSUE THREAD

**Issue by docularxu** [Linaro/uadk_engine#171]
https://github.com/Linaro/uadk_engine/blob/f1c812781059e3d11378f1663057d854f6cce5ca/src/uadk_prov_cipher.c#L116

**Comment by docularxu** [comment]
As i read the code, ```uadk provider``` requires fetch the algorithm implementation from ```default provider```. This is not a good design. This means in every LIBCTX you load 'uadk_provider', you also need to load 'default' provider.

Please reconsider this design. 
1) Is there a way to avoid such dependency? can we only load the sw_cipher when necessary? 
2) if the EVP_CIPHER_fetch() returns NULL, can we handle it beautifully and let the uadk_provider still work?
3) if this is not avoid, we need highlight this dependency to the users. Highlight that to load UADK_PROVIDER you must load 'default' provider too.

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/uadk_engine/pull/174
