### ISSUE TITLE
error prints “do hw ciphers failed” when 'openssl speed -multi 80'

### ISSUE THREAD

**Issue by docularxu** [Linaro/uadk_engine#204]
On a machine with 96 cores, when running `openssl speed -multi 80` test, it creates 80 processes to do the encryption in parallel. During the test, a lot of error prints “do hw ciphers failed”. 

Expected: There should be no error prints in screen. If the hw ciphers fails, the uadk_provider should automatically switch to the default provider (software implementations).

Reproduce:
` openssl speed -provider uadk_provider -provider default -multi 80 -seconds 20 -elapsed -evp sm4-ctr
`

**Comment by docularxu** [comment]
The /var/log/uadk.log generated by this command is more than 132MB.
It cannot be uploaded. :(

Anyway, it's easy to reproduce the issue, as it's only one command. See above.

**Comment by gaozhangfei** [comment]
need enable  sw via cnf
