### ISSUE TITLE
Abnormal results when using cipher's provider

### ISSUE THREAD

**Issue by Liulongfang** [Linaro/uadk_engine#215]
1. Using randomly generated 1024 own files for SM4 algorithm encryption, the ciphertext generated by the provider is only 1024 bytes. The results generated by openssl soft calculation and uadk_engine are both 1040 bytes.

2.Use unaligned 1032 byte files for provider testing. Both openssl soft calculation and uadk_engine can get results normally. The provider will report an error:
PROV_R_WRONG_FINAL_BLOCK_LENGTH

**Comment by gaozhangfei** [comment]
贴个命令好重现啊

**Comment by gaozhangfei** [comment]
master: uadk_engine: release 1.4

dd if=/dev/random of=test_data bs=1 count=1024
[root@8e1ad57985bf uadk_engine]# openssl enc -aes-128-cbc -in test_data -out out1 -K '1234567890123456' -iv '1234567890123456' -provider uadk_provider -p
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
salt=80FFFFFF00000000
key=12345678901234560000000000000000
iv =12345678901234560000000000000000
[root@8e1ad57985bf uadk_engine]# openssl enc -aes-128-cbc -in test_data -out out2 -K '1234567890123456' -iv '1234567890123456' -provider default -p
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
salt=80FFFFFF00000000
key=12345678901234560000000000000000
iv =12345678901234560000000000000000
[root@8e1ad57985bf uadk_engine]# ll out*
-rw-r--r-- 1 root root 1040 Jun 17 10:53 out1
-rw-r--r-- 1 root root 1040 Jun 17 10:53 out2

**Comment by gaozhangfei** [comment]
[root@8e1ad57985bf uadk_engine]# dd if=/dev/random of=test_data1 bs=1 count=1032
1032+0 records in
1032+0 records out
1032 bytes (1.0 kB, 1.0 KiB) copied, 0.00240295 s, 429 kB/s
[root@8e1ad57985bf uadk_engine]# openssl enc -aes-128-cbc -in test_data1 -out out1 -K '1234567890123456' -iv '1234567890123456' -provider uadk_provider -p
hex string is too short, padding with zero bytes to length
hex string is too short, padding with zero bytes to length
salt=80FFFFFF00000000
key=12345678901234560000000000000000
iv =12345678901234560000000000000000
