### ISSUE TITLE
Bug, engine the async module may trigger a core dump.

### ISSUE THREAD

**Issue by wangzengliang123** [Linaro/uadk_engine#221]
static void *async_poll_process_func(void *args)
{
	struct async_poll_task *task;
	struct async_op *op;
	int ret, idx;

	while (uadk_e_get_async_poll_state()) {
		if (sem_wait(&poll_queue.full_sem)) {
			if (errno == EINTR) {
				/* sem_wait is interrupted by interrupt, continue */
				continue;
			}
		}

		task = async_get_queue_task();
		if (!task) {
			(void)sem_post(&poll_queue.full_sem);
			usleep(1);
			continue;
		}

		op = task->op;
		idx = op->idx;
		ret = async_recv_func[task->type](task->ctx);
		if (!poll_queue.is_recv && op->job) {
			op->done = 1;
			op->ret = ret;
			async_wake_job(op->job);
			async_free_poll_task(idx, 0);
		}
	}

	return NULL;
}
void async_poll_task_free(void)
{
	struct async_poll_task *task;
	int error;

	/* Disable async poll state first */
	uadk_e_set_async_poll_state(DISABLE_ASYNC_POLLING);

	error = pthread_mutex_lock(&poll_queue.async_task_mutex);
	if (error)
		return;

	task = poll_queue.head;
	if (task)
		OPENSSL_free(task);

	poll_queue.head = NULL;

	pthread_mutex_unlock(&poll_queue.async_task_mutex);
	pthread_attr_destroy(&poll_queue.thread_attr);
	sem_destroy(&poll_queue.empty_sem);
	sem_destroy(&poll_queue.full_sem);
	pthread_mutex_destroy(&poll_queue.async_task_mutex);
}

sem_wait is block, if main thread end, destroy  poll_queue.full_sem , async thread block sem_wait ，will be
The futex facility returned an unexpected error code.
Aborted (core dumped)

**Comment by wangzengliang123** [comment]
LD_PRELOAD=/usr/lib64/libasan.so.6 openssl engine uadk_engine -c -t 
Adding asan will have a greater chance of triggering this bug.

**Comment by wangzengliang123** [comment]
why set async thread DETACHED?
async use main thread var

**Comment by gaozhangfei** [comment]
https://github.com/Linaro/uadk_engine/pull/222
