### ISSUE TITLE
Some places missing error handlings of pthread_mutex_lock

### ISSUE THREAD

**Issue by anson-lo** [Linaro/uadk_engine#97]
Hi, there are some places missing handling the possible errors that return from pthread_mutex_lock that are not consistent.

**unhandled**
https://github.com/Linaro/uadk_engine/blob/8f9bf25903a019fde04761a0c1dd2757cd680a16/src/v1/utils/engine_log.c#L98-L100

https://github.com/Linaro/uadk_engine/blob/8f9bf25903a019fde04761a0c1dd2757cd680a16/src/v1/utils/engine_log.c#L115-L117

**handled**
https://github.com/Linaro/uadk_engine/blob/8f9bf25903a019fde04761a0c1dd2757cd680a16/src/v1/wdmngr/wd_queue_memory.c#L391-L393

https://github.com/Linaro/uadk_engine/blob/8f9bf25903a019fde04761a0c1dd2757cd680a16/src/v1/wdmngr/wd_queue_memory.c#L397-L400

**Comment by gaozhangfei** [comment]
could you send pr, thanks

**Comment by anson-lo** [comment]
OK.
I have a question. Could all these cases be safely handled by checking the return values and directly returning to the callers?

**Comment by gaozhangfei** [comment]
The code is directly copy from kae, which is used in product.

I think in normal case we can simply ignore the return value.
https://www.man7.org/linux/man-pages/man3/pthread_mutex_lock.3p.html
 The mutex object referenced by mutex shall be locked by a call to
       pthread_mutex_lock() that returns zero or [EOWNERDEAD].  If the
       mutex is already locked by another thread, the calling thread
       shall block until the mutex becomes available.
